// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using ViaroAPP.Server.Data;

#nullable disable

namespace ViaroAPP.Server.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250430212549_InitialCreate")]
    partial class InitialCreate
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.28")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Asiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodigoAsiento")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<float?>("Credito")
                        .HasColumnType("real");

                    b.Property<float?>("Debito")
                        .HasColumnType("real");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.HasKey("Id");

                    b.ToTable("Asientos");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Calculo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreCalculo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Calculos");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Cargo", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("NombreCargo")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.HasKey("Id");

                    b.ToTable("Cargos");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Empleado", b =>
                {
                    b.Property<string>("Codigo")
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<string>("ApellidoMaterno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("ApellidoPaterno")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Cedula")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<int?>("IdCargo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<float?>("SalarioHora")
                        .HasColumnType("real");

                    b.Property<string>("SegundoNombre")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.HasKey("Codigo");

                    b.HasIndex("Cedula")
                        .IsUnique();

                    b.HasIndex("IdCargo");

                    b.ToTable("Empleados");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Planilla", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("CodigoEmpleado")
                        .IsRequired()
                        .HasMaxLength(4)
                        .HasColumnType("nvarchar(4)");

                    b.Property<float?>("DescuentoAcreedores")
                        .HasColumnType("real");

                    b.Property<float?>("DescuentoSeguro")
                        .HasColumnType("real");

                    b.Property<DateTime?>("FechaPlanilla")
                        .HasColumnType("datetime2");

                    b.Property<int?>("HorasTrabajadas")
                        .HasColumnType("int");

                    b.Property<int?>("IdCalculo")
                        .IsRequired()
                        .HasColumnType("int");

                    b.Property<float?>("ImpuestoSobreRenta")
                        .HasColumnType("real");

                    b.Property<float?>("PrimaProducción")
                        .HasColumnType("real");

                    b.Property<float?>("SeguroEducativo")
                        .HasColumnType("real");

                    b.Property<float?>("SeguroSocial")
                        .HasColumnType("real");

                    b.Property<float?>("Sinticop")
                        .HasColumnType("real");

                    b.Property<float?>("Sobretiempo")
                        .HasColumnType("real");

                    b.Property<float?>("Total")
                        .HasColumnType("real");

                    b.Property<float?>("TotalDescuentos")
                        .HasColumnType("real");

                    b.Property<float?>("TotalIngresos")
                        .HasColumnType("real");

                    b.HasKey("Id");

                    b.HasIndex("CodigoEmpleado");

                    b.HasIndex("IdCalculo");

                    b.ToTable("Planillas");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Empleado", b =>
                {
                    b.HasOne("ViaroAPP.Server.Data.Entities.Cargo", "Cargo")
                        .WithMany("Empleados")
                        .HasForeignKey("IdCargo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Cargo");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Planilla", b =>
                {
                    b.HasOne("ViaroAPP.Server.Data.Entities.Empleado", "Empleado")
                        .WithMany("Planillas")
                        .HasForeignKey("CodigoEmpleado")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("ViaroAPP.Server.Data.Entities.Calculo", "Calculo")
                        .WithMany("Planillas")
                        .HasForeignKey("IdCalculo")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Calculo");

                    b.Navigation("Empleado");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Calculo", b =>
                {
                    b.Navigation("Planillas");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Cargo", b =>
                {
                    b.Navigation("Empleados");
                });

            modelBuilder.Entity("ViaroAPP.Server.Data.Entities.Empleado", b =>
                {
                    b.Navigation("Planillas");
                });
#pragma warning restore 612, 618
        }
    }
}
